# watches the log file and pushes to loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pipeline-logs
    static_configs:
      - targets: [localhost]
        labels:
          job: pipeline-logs
          app: pipeline
          # pick up your single file (or change to *.log to catch multiple)
          __path__: /var/log/pipeline/app.log
