{
 "title": "MARKET DATA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" },
   {
    "name": "Ticker",
    "query": "SELECT DISTINCT symbol\nFROM ticks_to_minute\nORDER BY symbol"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Price - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    anyHeavyMerge(open) AS open\r\nFROM minute_bars\r\nWHERE symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Price - ${Ticker}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    anyHeavyMerge(open) AS open,\r\n    symbol\r\nFROM minute_bars\r\nWHERE $__timeFilter(minute)\r\n  AND symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nGROUP BY symbol, minute\r\nORDER BY minute DESC\r\n"
    }
   ]
  },
  {
   "title": "Trading Volume - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    sumMerge(volume) AS total_vol\r\nFROM minute_bars\r\nWHERE $__timeFilter(minute)\r\n  AND symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\n"
    }
   ]
  },
  {
   "title": "Notional Volume - ${Ticker}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    sum(v * o) AS total_vol_usd\r\nFROM\r\n(\r\n    SELECT\r\n        minute,\r\n        sumMerge(volume) AS v,\r\n        anyHeavyMerge(open) AS o\r\n    FROM minute_bars\r\n    WHERE $__timeFilter(minute)\r\n      AND symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\n    GROUP BY minute\r\n) sub\r\n"
    }
   ]
  },
  {
   "title": "Trading Volume - ${Ticker}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    minute,\r\n    sumMerge(volume) AS volume,\r\n    symbol\r\nFROM minute_bars\r\nWHERE $__timeFilter(minute)\r\n  AND symbol = concat('BINANCE:', '${Ticker}', 'USDT')\r\nGROUP BY symbol, minute\r\nORDER BY minute DESC\r\n"
    }
   ]
  }
 ]
}