{
 "title": "Portfolio Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Current Portfolio",
   "type": "table",
   "gridPos": { "h": 15, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT strategy_name, strategy_description, symbol, quantity, portfolio_value\r\nFROM portfolio_db_key\r\nORDER BY strategy_name"
    }
   ]
  },
  {
   "title": "Porfolio Performance Over Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  portfolio_value AS \" \",\r\n  CONCAT(strategy_name, ' ', symbol) as metric\r\nFROM portfolio_db_ts\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Recent Approved Trades",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  strategy_name,\r\n  extract(execution_logic, 'decision: (\\\\w+)') AS decision,\r\n  symbol,\r\n  quantity,\r\n  executed_price,\r\n  quantity * executed_price as trade_value,\r\n  approval_comment\r\nFROM execution_db\r\nWHERE approval_status == 'Y' and decision != 'HOLD' and decision != ''\r\nORDER BY time DESC\r\nLIMIT 10\r\n"
    }
   ]
  },
  {
   "title": "Recent Rejected Trades",
   "type": "table",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  strategy_name,\r\n  extract(execution_logic, 'decision: (\\\\w+)') AS decision,\r\n  symbol,\r\n  quantity,\r\n  model_price,\r\n  quantity * model_price as trade_value,\r\n  approval_comment\r\nFROM execution_db\r\nWHERE approval_status == 'N' and decision != 'HOLD'\r\nORDER BY time DESC\r\nLIMIT 10\r\n"
    }
   ]
  }
 ]
}