{
 "title": "SYSTEMATIC TRADING",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Portfolio",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT strategy_name as Strategy, symbol as Symbol, quantity as Quantity, market_value as Market_Position, cash_balance as Cash_Position, portfolio_value as Net_Value, status as Status\r\nFROM portfolio_db_key\r\nORDER BY strategy_name\r\n\r\n"
    }
   ]
  },
  {
   "title": "Porfolio Performance Over Time",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  time,\r\n  portfolio_value AS \" \",\r\n  CONCAT(strategy_name, ' ', symbol) AS metric\r\nFROM portfolio_db_ts\r\nWHERE $__timeFilter(time)\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Recent Trades",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT time, strategy_name, symbol, signal, quantity, executed_price * quantity as trade_value, approval_status, approval_comment\r\nFROM execution_db\r\nORDER BY time DESC\r\nLIMIT 10\r\n"
    }
   ]
  }
 ]
}