{
 "title": "Market Data",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Current ETH Price",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT price, timestamp\r\nFROM ticks_db\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "ETH Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 1) MILLISECOND\r\n  ) AS time,\r\n  avg(price) AS price\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "Volume ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume) AS total_vol\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "ETH OHLCV",
   "type": "candlestick",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 15) MILLISECOND\r\n  ) AS time,\r\n    any(price) AS open,\r\n    anyLast(price) AS close,\r\n    max(price) AS high,\r\n    min(price) AS low\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Volume (USD)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(volume * price) AS total_vol_usd\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\n"
    }
   ]
  },
  {
   "title": "ETH Volume",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  toStartOfInterval(\r\n    timestamp,\r\n    INTERVAL toUInt32($__interval_ms * 20) MILLISECOND\r\n  ) AS time,\r\n  sum(volume) as volume\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp)\r\nGROUP BY time\r\nORDER BY time\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Market Data (Table View)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\r\n*\r\nFROM ticks_db\r\nORDER BY timestamp DESC\r\nLIMIT 20\r\n"
    }
   ]
  }
 ]
}