{
 "title": "System Monitoring",
 "description": "Monitors the Kafka producer",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds_clickhouse", "query": "grafana-clickhouse-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Avg Websocket Lag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_websocket_lag) AS websocket_lag\r\nFROM websocket_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Avg Consumer Lag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(avg_timestamp) AS minute,\r\n    avg(avg_processing_lag) AS processing_lag\r\nFROM processing_diagnostics\r\nWHERE $__timeFilter(avg_timestamp)\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "New Rows / Minute",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfMinute(timestamp) AS minute,\r\n    count(timestamp) AS ticksPerMinute\r\nFROM ticks_db\r\nWHERE timestamp >= now() - INTERVAL 5 MINUTE\r\nGROUP BY minute\r\nORDER BY minute DESC\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Total Rows",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    count(timestamp) AS total_rows\r\nFROM ticks_db\r\nWHERE $__timeFilter(timestamp);\r\n"
    }
   ]
  },
  {
   "title": "Table Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    table,\r\n    round(sum(bytes) / 1024 / 1024, 2) AS size_mb\r\nFROM system.parts\r\nWHERE database = currentDatabase()\r\n  AND table = 'ticks_db'\r\nGROUP BY table;\r\n"
    }
   ]
  }
 ]
}